name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  elixir_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '26.0'
          version-type: 'loose'

      - name: Restore deps cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key:
            ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}-git-${{
            github.sha }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
            ${{ runner.os }}-deps

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Remove compiled files
        run: mix clean

      - name: Compile dependencies
        run: mix compile
        env:
          MIX_ENV: test

      - name: Format
        run: |
          mix format --check-formatted

      - name: Lint
        run: |
          mix credo

      - name: Test
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test --trace
        env:
          MIX_ENV: test

      - name: Check code coverage
        run: mix coveralls
        env:
          MIX_ENV: test

      - name: Upload coverage to coveralls
        run: mix coveralls.github
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
