name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  elixir_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '26.0'
          version-type: 'loose'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          if ! [ -x "$(command -v stack)" ]; then
            curl -sSL https://get.haskellstack.org/ | sh
          else
            echo "Stack is already installed."
          fi

      - name: Build parser
        run: |
          stack setup --install-ghc
          mkdir -p build runnable
          stack install cryptonite
          make build
        working-directory: ./mds-converter

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: |
          mix deps.get

      - name: Compile code
        run: |
          mix compile
        env:
          MIX_ENV: test

      - name: Format
        run: |
          mix format --check-formatted

      - name: Lint
        run: |
          mix credo

      - name: Test
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test --trace
        env:
          MIX_ENV: test

      - name: Check code coverage
        run: mix coveralls
        env:
          MIX_ENV: test

      - name: Upload coverage to coveralls
        run: mix coveralls.github
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
